### ISSUE TITLE
1.2.0 Crash with TConstruct

### ISSUE THREAD

**Issue by Thiana** [romelo333/notenoughwands#1]
Details http://openeye.openmods.info/crashes/12667c28c44a82ceea415633e90053e6

To replicate, install TC/Mantle/NEW. Get a Lumber Axe of some sort, and chop down a tree. Crash.

The crash does not occur with 1.1.2

Thanks :)

**Comment by Thiana** [comment]
PS: You may want to update the CF project page with a link to here (or enable CF issues)

**Comment by McJty** [comment]
Will be fixed in next version (which I'm about to release in a few moments)
