### ISSUE TITLE
Disconnect from server when using hotkey to switch wand mode

### ISSUE THREAD

**Issue by Febilian** [romelo333/notenoughwands#10]
Seems to happen with every wand I've tried with more than one mode, regardless of the hotkey it's bound to. It gives the "Connection reset by peer" message when it's attempted, but the client doesn't crash and I can log back in right away.

I'm on the latest 1.8.9 version(to my knowledge it's the latest).

This is from the client's end:

http://pastebin.com/ddezyurQ

**Comment by McJty** [comment]
I will need the entire server-side log

**Comment by Febilian** [comment]
https://paste.ee/p/g2ZH3#

Will that work?

**Comment by McJty** [comment]
What wand where you using in this case?

**Comment by McJty** [comment]
For now I have no idea what causes this. Two things. Can you also provide me with the full client-side log? And two, can you reproduce this bug also in a smaller modpack containing only not enough wands? Also is this single player or server?

**Comment by McJty** [comment]
Hmm. It is possible that I found the issue

**Comment by McJty** [comment]
Yes, this will be the issue. Fixed in next release
