### ISSUE TITLE
Crash on load

### ISSUE THREAD

**Issue by Dexy2811** [romelo333/notenoughwands#105]
So when I tried to load the modpack with the version 1.12-1.7.1 it crashed and gave me this error:
`The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: Lromelo333/notenoughwands/proxy/CommonProxy;
`

hope this report helps

**Comment by Dexy2811** [comment]
This is my latest crash report
[crash-2019-09-19_09.34.34-client.txt](https://github.com/romelo333/notenoughwands/files/3629993/crash-2019-09-19_09.34.34-client.txt)

**Comment by McJty** [comment]
Do you have (the correct version) of mcjtylib mod?

**Comment by Dexy2811** [comment]
okay yep I just had to update the mods 👍
