### ISSUE TITLE
Crash while attempting to launch

### ISSUE THREAD

**Issue by Luminous-Journey** [romelo333/notenoughwands#113]
when i attempt to launch minecraft with create 0.3.1, Easypaxellite, jei, optifine, worldedit, and notenoughwands(NEW) 3.0.1 with forge 36.1.6 i get an error saying NEW has class loading errors java.lang.NoClassDefFoundError: mcjty/lib/modules/IModule
[crash-2021-05-11_16.10.36-fml.txt](https://github.com/romelo333/notenoughwands/files/6462450/crash-2021-05-11_16.10.36-fml.txt)
[latest.log](https://github.com/romelo333/notenoughwands/files/6462453/latest.log)

**Comment by Luminous-Journey** [comment]
pls help

**Comment by Luminous-Journey** [comment]
just tested rlly quick the other mods dont effect the crash

**Comment by McJty** [comment]
You need McJtyLib
