### ISSUE TITLE
Illuminating wand caused crash after placing on a carpenter's block.

### ISSUE THREAD

**Issue by Porthiir** [romelo333/notenoughwands#12]
Here's the crash log, I was advised to post it here: http://pastebin.com/kSDzt9ia

**Comment by Porthiir** [comment]
Was just informed, it's possible it wasn't the one placed on a carpenter's slope, but rather one placed underneath a Decocraft bench.

**Comment by McJty** [comment]
This is a bug in DecoCraft and not in Not Enough Wands. The crash is happening in a DecoCraft method
