### ISSUE TITLE
Crash on startup 1.19.2-5.0.0

### ISSUE THREAD

**Issue by jcnruad900** [romelo333/notenoughwands#120]
[crash-2023-02-20_20.13.00-fml.txt](https://github.com/romelo333/notenoughwands/files/10787287/crash-2023-02-20_20.13.00-fml.txt)

**Comment by jcnruad900** [comment]
I have mcjty lib btw

**Comment by McJty** [comment]
Update Not Enough Wands. You need 5.0.1
