### ISSUE TITLE
NeoForge 1.21.1: error getting an Ingredient's tooltip (JEI)

### ISSUE THREAD

**Issue by Daltaxy** [romelo333/notenoughwands#123]
Hello. Unsure if this is rather a JEI issue, but this mod seems to be directly concerned

It happens with all of Not Enough Wands' items it seems:
<details><summary>Error Example</summary>
<p>

<html>
<body>

[24Sep2024 15:56:00.553] [Render thread/ERROR] [mezz.jei.common.util.ErrorUtil/]: Caught an error getting an Ingredient's tooltip:
--
4485 |  
4486 | -- Ingredient --
4487 | Details:
4488 | Name: Master Protection Wand
4489 | Mod's Name: Not Enough Wands
4490 | Registry Name: notenoughwands:master_protection_wand
4491 | Class Name: class net.minecraft.world.item.ItemStack
4492 | toString Name: 1 notenoughwands:master_protection_wand
4493 | JSON: {"id":"notenoughwands:master_protection_wand"}
4494 | Ingredient Type for JEI: class net.minecraft.world.item.ItemStack
4495 | Error Info gathered from JEI: 1 notenoughwands:master_protection_wand notenoughwands:master_protection_wand components:{}
4496 |  
4497 | -- Stack Trace --
4498 |  
4499 | java.lang.NullPointerException: Cannot invoke "romelo333.notenoughwands.modules.wands.WandUsage.needsPower()" because "romelo333.notenoughwands.modules.wands.WandsConfiguration.cachedWandUsage" is null
4500 | at TRANSFORMER/notenoughwands@1.21-7.0.0/romelo333.notenoughwands.modules.wands.Items.GenericWand.needsPower(GenericWand.java:226)
4501 | at TRANSFORMER/notenoughwands@1.21-7.0.0/romelo333.notenoughwands.modules.wands.Items.GenericWand.appendHoverText(GenericWand.java:81)
4502 | at TRANSFORMER/notenoughwands@1.21-7.0.0/romelo333.notenoughwands.modules.protectionwand.items.ProtectionWand.appendHoverText(ProtectionWand.java:50)
4503 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.item.ItemStack.getTooltipLines(ItemStack.java:770)
4504 | at TRANSFORMER/jei@**.**.**.**/mezz.jei.library.render.ItemStackRenderer.getTooltip(ItemStackRenderer.java:62)
4505 | at TRANSFORMER/jei@**.**.**.**/mezz.jei.library.render.ItemStackRenderer.getTooltip(ItemStackRenderer.java:22)
4506 | at TRANSFORMER/jei@**.**.**.**/mezz.jei.common.util.SafeIngredientUtil.getTooltip(SafeIngredientUtil.java:61)
4507 | at TRANSFORMER/jei@**.**.**.**/mezz.jei.gui.ingredients.ListElementInfo.getTooltipStrings(ListElementInfo.java:127)
4508 | at TRANSFORMER/jei@**.**.**.**/mezz.jei.gui.search.ElementPrefixParser.lambda$new$2(ElementPrefixParser.java:77)
4509 | at TRANSFORMER/jei@**.**.**.**/mezz.jei.core.search.PrefixInfo.getStrings(PrefixInfo.java:40)
4510 | at TRANSFORMER/jei@**.**.**.**/mezz.jei.core.search.PrefixedSearchable.getStrings(PrefixedSearchable.java:20)
4511 | at TRANSFORMER/jei@**.**.**.**/mezz.jei.gui.search.ElementSearch.add(ElementSearch.java:63)
4512 | at TRANSFORMER/jei@**.**.**.**/mezz.jei.gui.ingredients.IngredientFilter.addIngredient(IngredientFilter.java:116)
4513 | at TRANSFORMER/jei@**.**.**.**/mezz.jei.gui.ingredients.IngredientFilter.<init>(IngredientFilter.java:89)
4514 | at TRANSFORMER/jei@**.**.**.**/mezz.jei.gui.startup.JeiGuiStarter.start(JeiGuiStarter.java:123)
4515 | at TRANSFORMER/jei@**.**.**.**/mezz.jei.neoforge.plugins.neoforge.NeoForgeGuiPlugin.registerRuntime(NeoForgeGuiPlugin.java:39)
4516 | at TRANSFORMER/jei@**.**.**.**/mezz.jei.library.startup.JeiStarter.lambda$start$2(JeiStarter.java:152)
4517 | at TRANSFORMER/jei@**.**.**.**/mezz.jei.library.load.PluginCaller.callOnPlugins(PluginCaller.java:25)
4518 | at TRANSFORMER/jei@**.**.**.**/mezz.jei.library.startup.JeiStarter.start(JeiStarter.java:152)
4519 | at TRANSFORMER/jei@**.**.**.**/mezz.jei.neoforge.startup.StartEventObserver.transitionState(StartEventObserver.java:170)
4520 | at TRANSFORMER/jei@**.**.**.**/mezz.jei.neoforge.startup.StartEventObserver.onEvent(StartEventObserver.java:120)
4521 | at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.ConsumerEventHandler.invoke(ConsumerEventHandler.java:26)
4522 | at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:350)
4523 | at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:315)
4524 | at TRANSFORMER/neoforge@21.1.61/net.neoforged.neoforge.client.ClientHooks.onRecipesUpdated(ClientHooks.java:663)
4525 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.multiplayer.ClientPacketListener.handleUpdateRecipes(ClientPacketListener.java:1506)
4526 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.protocol.game.ClientboundUpdateRecipesPacket.handle(ClientboundUpdateRecipesPacket.java:32)
4527 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.protocol.game.ClientboundUpdateRecipesPacket.handle(ClientboundUpdateRecipesPacket.java:13)
4528 | at TRANSFORMER/neoforge@21.1.61/net.neoforged.neoforge.network.registration.NetworkRegistry.handlePacketUnchecked(NetworkRegistry.java:824)
4529 | at TRANSFORMER/neoforge@21.1.61/net.neoforged.neoforge.network.handling.IPayloadContext.handle(IPayloadContext.java:108)
4530 | at TRANSFORMER/neoforge@21.1.61/net.neoforged.neoforge.network.filters.GenericPacketSplitter.lambda$receivedPacket$0(GenericPacketSplitter.java:154)
4531 | at TRANSFORMER/neoforge@21.1.61/net.neoforged.neoforge.network.handling.ClientPayloadContext.enqueueWork(ClientPayloadContext.java:31)
4532 | at TRANSFORMER/neoforge@21.1.61/net.neoforged.neoforge.network.filters.GenericPacketSplitter.receivedPacket(GenericPacketSplitter.java:154)
4533 | at TRANSFORMER/neoforge@21.1.61/net.neoforged.neoforge.network.filters.GenericPacketSplitter.handle(GenericPacketSplitter.java:69)
4534 | at TRANSFORMER/neoforge@21.1.61/net.neoforged.neoforge.network.handling.MainThreadPayloadHandler.lambda$handle$0(MainThreadPayloadHandler.java:16)
4535 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:60)
4536 | at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
4537 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:148)
4538 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23)
4539 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122)
4540 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:111)
4541 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.Minecraft.runTick(Minecraft.java:1155)
4542 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.Minecraft.run(Minecraft.java:807)
4543 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.main.Main.main(Main.java:230)
4544 | at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
4545 | at java.base/java.lang.reflect.Method.invoke(Unknown Source)
4546 | at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:136)
4547 | at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:124)
4548 | at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:32)
4549 | at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:118)
4550 | at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
4551 | at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
4552 | at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
4553 | at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.run(Launcher.java:103)
4554 | at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.main(Launcher.java:74)
4555 | at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
4556 | at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
4557 | at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210)
4558 | at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69)

</body>
</html>

</p>
</details> 

latest.log: https://mclo.gs/y2Z8QuJ
debug.log if needed: https://mclo.gs/nEQ5k0Y

NeoForge loader 21.1.61
1.21.1
notenoughwands-1.21-7.0.0.jar

edit: removed useless info

**Comment by McJty** [comment]
I'll check it out soon

**Comment by McJty** [comment]
Should be fixed now
