### ISSUE TITLE
Swapping Wand does not update surrounding blocks

### ISSUE THREAD

**Issue by founderio** [romelo333/notenoughwands#16]
Example:
Replace grass with something else & tall grass will remain behind until it is updated.
![screenshot from 2016-05-28 00-22-28](https://cloud.githubusercontent.com/assets/6136865/15622571/5c355098-246a-11e6-9dd0-648ab9f59f33.png)
Version: 1.3.3 (MC 1.9.4)

**Comment by McJty** [comment]
Fixed next release
