### ISSUE TITLE
[1.10.2] Wands not using RF even when configed to use

### ISSUE THREAD

**Issue by vrork** [romelo333/notenoughwands#26]
Title

**Comment by McJty** [comment]
Show me how you configured this. It is working fine for me

**Comment by vrork** [comment]
http://pastebin.com/a8zZxGpY

**Comment by McJty** [comment]
You set I:capturing_wand_needsrf to 0 (as well as for the other wands). That disables RF usage. You must make sure to set at least some number there (i.e. how much RF you want it to use)

**Comment by vrork** [comment]
Shit. I swear i had set the needxp to that and the need rf to 100. You
wouldnt happen to know the config that is being used on forgecraft server
would you?

**Comment by McJty** [comment]
Most wands there are set to maxrf 100000 and then between 100 and 2000 depending on how powerful the effect is considered to be (so capturing wand is more powerful, building wand less)

**Comment by vrork** [comment]
Thanks. That helps a lot (exact values would be even better but hey, that
is better than nothing.)

Totally unrelated, any idea if they plan on looking at the TAIGA mod and
the Tinkers I/O mod?
