### ISSUE TITLE
Illumination Wand Orbs Cause Texture Transparency Issues

### ISSUE THREAD

**Issue by KirinDave** [romelo333/notenoughwands#34]
Hello, KirinDave from the Resonant Rise pack here. We ran across a bug where many tile entities get strange texture issues when illumination orbs enter the world, and illumination orbs start causing water to vanish behind them.

The reproduction is simple:

Place a sign on the wall, put an orb above and below. Or place a chest on the ground, and surround it with illumniation orbs. The exact point when people start to see the graphical glitch and its consistency do not seem constant among clients, but we cannot isolate for different hardware so that may just be a secondary issue.

**Comment by McJty** [comment]
Should probably be fixed next release. At least for the 1.10.2 version
