### ISSUE TITLE
Swapping Wand: Redstone Ore is being deleted

### ISSUE THREAD

**Issue by ZephyrWindSpirit** [romelo333/notenoughwands#4]
Modpack: Vaygrim's Chance 3 1.1
MC Version: 1.7.10
Not Enough Wands Version: 1.2.3

Issue: Using the Swapping Wand with Chisel Granite as the selected block and swapping out with redstone ore swaps the granite in place, but no redstone ore or dusts are being put into the inventory. This has been replicated with cobblestone, vanilla stone and dirt.

![2016-01-08_14 28 55](https://cloud.githubusercontent.com/assets/16616656/12211238/780dfb40-b614-11e5-89a0-a209a792156b.png)
![2016-01-08_14 29 07](https://cloud.githubusercontent.com/assets/16616656/12211243/7cfbb976-b614-11e5-976b-f58d1d710f33.png)

**Comment by r00sty** [comment]
I can confirm this problem is still present in 1.8.9-1.3.0, will update to latest version and test again.

**Comment by McJty** [comment]
I can reproduce this. I will fix this for the 1.9.4 version and the 1.8.9 version

**Comment by McJty** [comment]
Fixed next release for 1.8.9 and 1.9.4
