### ISSUE TITLE
Crash when hovering over certain wands

### ISSUE THREAD

**Issue by cauliflower69** [romelo333/notenoughwands#5]
Using the latest version for 1.8.9

https://youtu.be/8lvAMw9nXgc

**Comment by McJty** [comment]
We will check it out

**Comment by rckymtnrfc** [comment]
Here is what I'm seeing on the server side when this happens.

http://pastebin.com/ZQ8ywP3u

**Comment by cauliflower69** [comment]
@rckymtnrfc Thanks for the additional information

**Comment by McJty** [comment]
We will try to fix this today

**Comment by McJty** [comment]
We cannot reproduce this. We tried single player, server, anything. What version of Not Enough Wands are you using?

**Comment by cauliflower69** [comment]
1.2.4

**Comment by McJty** [comment]
Could you give us the full log? Both server and client?

**Comment by rckymtnrfc** [comment]
Client crash-log - http://pastebin.com/RhLD3sUE

Server log - http://pastebin.com/XH3gFQnf

I'm using Forge 1699, JEI 2.18.1.88 and NEW 1.2.4

**Comment by McJty** [comment]
Hmm, the client crash is actually in JEI

**Comment by rckymtnrfc** [comment]
I updated to 2.19.0.93 and now the client doesn't crash, I just disconnect from the client.

**Comment by rckymtnrfc** [comment]
from the server I mean.  I disconnect from the server.

**Comment by McJty** [comment]
Possibly fixed in 1.2.7
