### ISSUE TITLE
Viewing RF on wands

### ISSUE THREAD

**Issue by Leonyx1175** [romelo333/notenoughwands#52]
Not a bug, just a feature request. Would it be possible to include a way to show how much RF wands have (or have I just overlooked something)?

**Comment by Rahmiel** [comment]
There is a config for showing the durability bar when using RF, however it doesn't seem to be working. Version 1.10.2 for me by the way.

**Comment by McJty** [comment]
Hmm that option should be on by default and it works fine for me on 1.10.2. Can you show me your config?

**Comment by Leonyx1175** [comment]
I'm so sorry, I went on a hiatus not long after this post and this should have been closed awhile ago, it worked for me just fine then and does still with 1.12.
