### ISSUE TITLE
[1.12-1.5.7] Crash on Startup

### ISSUE THREAD

**Issue by Kris1432** [romelo333/notenoughwands#59]
Forge 2375
Version 1.12-1.5.7

Cause: Crash when starting the game.

Crashlog: https://pastebin.com/vLLLfyaY

**Comment by JasonKillsUs** [comment]
yep same here same specs

**Comment by McJty** [comment]
Until I solve this you will have to add the new Redstone Flux mod from CoFH

**Comment by Kris1432** [comment]
I am using that @McJty. Check line 129 on my crashlog.

**Comment by McJty** [comment]
hmm ok. I'll check it out

**Comment by McJty** [comment]
Fixed in upcoming 1.5.8 that is now in the curseforge approval queue
