### ISSUE TITLE
[1.12] Config [wandsettings] no longer works

### ISSUE THREAD

**Issue by donqixot** [romelo333/notenoughwands#61]
Thank you again for this mod!

I am not sure if this happened only since [1.12] or after some version update, but config section [wandsettings] became empty and now even if I try to insert config from older version, it no longer works. Is this by design?

**Comment by Knito58** [comment]
MC 1.12
Forge 14.21.1.2395
NEW 1.12-1.5.8

Section general
S:wandSettingPreset=normal_rf

does not work. The setting is always "default" and uses xp instead of rf.

**Comment by McJty** [comment]
Will be fixed next release
