### ISSUE TITLE
[1.12]  wandsettings availability not configurable

### ISSUE THREAD

**Issue by Knito58** [romelo333/notenoughwands#65]
MC 1.12
Forge 14.21.1.2420
NEW 1.12-1.5.9

_# Is this wand available? (0=no, 1=not craftable, 2=craftable advanced, 3=craftable normal)     I:acceleration_wand_availability=3_

Behaves as if "2" was set.

**Comment by Tetrajak** [comment]
I'll also add that this is happening in 1.12-1.6.0, and that setting a wand to "0" doesn't change its availability either.

**Comment by chokoth** [comment]
Still seeing this happen in 1.12-1.6.1. This on the radar to be fixed?

**Comment by McJty** [comment]
I try to find time to fix this

**Comment by McJty** [comment]
Ok, this is in fact no longer possible in 1.12 with thew new json recipes. You have to use CraftTweaker to fix this issue. I'll remove the option in the next release as it is confusing

**Comment by GrumpyChunks** [comment]
Would it be possible to update the documentation (https://minecraft.curseforge.com/projects/not-enough-wands) to reflect this. I've just been digging around the config files and (old?) source code for the past hour or so, trying to figure out why this setting doesn't seem to work?
