### ISSUE TITLE
[1.12.1] Blocks from Biomes'O'Plenty mod are mixed up by swapping wand

### ISSUE THREAD

**Issue by donqixot** [romelo333/notenoughwands#66]
BoP has 9 variations of grass (biomesoplenty:grass:0 thru biomesoplenty:grass:8). When using swapping wand to replace those, instead of getting correct grass type, you always get biomesoplenty:grass:0 (spectral moss). Except 2 cases - (1) when  you replace biomesoplenty:grass:3 (sandy grass), you get back biomesoplenty:grass:1 (overgrown stone); (2) when you replace biomesoplenty:grass:4 (silty grass), you get back biomesoplenty:grass:2 (loamy grass). For comparison, using shovel with silk touch gives you correct grass type.

I am using BoP version 1.12-7.0.0.2291, not-enough-wands version 1.12-1.5.9, forge 1.12.1-14.22.0.2453. The only other mod present is jei_1.12-4.7.5.85.

I saw same issue in 1.12 and earlier versions of forge.

This issue is very similar to https://github.com/romelo333/notenoughwands/issues/60

**Comment by McJty** [comment]
Likely fixed next release
