### ISSUE TITLE
Deleting Blocks when using the Moving Wand

### ISSUE THREAD

**Issue by SnowShock35** [romelo333/notenoughwands#68]
#### Issue Specification

* Minecraft 1.12.2
* Minecraft Forge 14.23.0.2529
* Not Enough Wands 1.12-1.5.9

#### Issue Description

Placing a full block in the same space as a cable (from Thermal Dynamics) with the moving wand deletes the cable. There should be checks for non solid blocks if they yet to exist. 

***

~~Apologies for the current lack of information on the issue. When I have more detail of the issue I will update this.~~

**Comment by McJty** [comment]
I can reproduce this with a torch. I will fix this now

**Comment by McJty** [comment]
Fixed next release
