### ISSUE TITLE
New update crashes without chisel&bits mod installed - 1.8.9

### ISSUE THREAD

**Issue by Avalonzo** [romelo333/notenoughwands#7]
As mentioned above I kept have a crash and it mentioned chisel&bits which I thought was strange as I didn't have it installed. I found I didn't crash if I disabled Not Enough Wands & once I re-enabled N.E.W. I once again got the Chisel&bits error so installed Chisel&bits and no more crashing so it would seems it's now required and no mention of its requirement on the curseforge page.

[crash-2016-01-24_20.34.08-client.txt]
(https://github.com/romelo333/notenoughwands/files/102540/crash-2016-01-24_20.34.08-client.txt)

**Comment by McJty** [comment]
Will make a fix later today

**Comment by Avalonzo** [comment]
Ok thank you :D
