### ISSUE TITLE
[1.12.2] Swapping Wand w/ Draconic Evolution Causes Issues

### ISSUE THREAD

**Issue by SnowShock35** [romelo333/notenoughwands#71]
#### Issue Details

- Minecraft 1.12.2
- Minecraft Forge 14.23.1.2583
- NotEnoughWands 1.12-1.6.0
- Other:
  - Draconic Evolution 1.12-2.3.7.278
  - Brandon's Core 1.12-2.3.7-140

#### Issue Description

When using the swapping wand on end or nether Draconium Ore it returns the overworld variant for some odd reason. I've tried to figure out why but don't see how or why it would occur. all three variants have separate metadata so should be able to distinguish between them

**Comment by McJty** [comment]
I'll check it out later

**Comment by SnowShock35** [comment]
ty :heart:

**Comment by McJty** [comment]
This could be a bug in Draconic Evolution itself. If I do this:

        ItemStack item = block.getItem(world, pos, state);

Where the block points to a nether variant of draconium ore I still get an itemstack that indicates normal Draconium ore. Block.getItem() uses Item.getItemFromBlock(this) and Block.damageDropped(state). Perhaps submitting a link to this issue on Draconic Evolution's github and then we can see how we can work this out

**Comment by brandon3055** [comment]
Found the problem. Your calling block.getItem when according to this you should be calling getPickBlock
![](http://ss.brandon3055.com/2xuddvd.png)
I only override getPickBlock but i will add an override for getItem to fix issues like this.

**Comment by McJty** [comment]
Ok. I can call getPickBlock too. I just hope that no mod depends on the the RayTraceResult being non null because I can't supply that parameter
