### ISSUE TITLE
[1.12.2] Items Being Voided - Mod Interaction w/ Refined Storage

### ISSUE THREAD

**Issue by SnowShock35** [romelo333/notenoughwands#72]
#### Issue Details

- Minecraft 1.12.2
- Minecraft Forge 14.23.1.2587
- Not Enough Wands 1.12-1.6.0
- Other Mods:
  - Refined Storage 1.5.31

#### Issue Description

Using the displacement wand on Refined Storage's Crafter Blocks leads to loss of inventory (of patterns)

###### What should happen?

The inventory is retained when being displaced (NBT?)

###### What actually happens?

The patterns are voided.

###### Steps to Reproduce

1. Place down a Refined Storage Crafter
2. Place some patterns in it
3. Close the GUI and use the displacement wand on the tile
4. Re-Open the GUI to find the patterns are no longer there

*** 

Issue reported to raoulvdberge/refinedstorage#1622

**Comment by SnowShock35** [comment]
Solution: Add blacklist to configuration file that allows blacklisting displacement of blocks **or** Config option to disallow displacement of tiles

**Comment by McJty** [comment]
Will add to blacklist if you can tell me the registry name (i.e. internal name) of the block (format modid:name)

**Comment by SnowShock35** [comment]
At college right now. Raoul might be able to let you know if he's about.

**Comment by McJty** [comment]
All Refined Storage blocks are added to the blacklist now
