### ISSUE TITLE
1.12.2 Moving wand changes spawners back to original mob

### ISSUE THREAD

**Issue by ZephyrWindSpirit** [romelo333/notenoughwands#73]
FTB Revelation 1.2.0
Minecraft Forge 14.23.1.2573
not enough wands 1.12 1.6.0
mob_grinding_utils 0.3.4

Using Mob grinding utilities, I obtained an enderman spawn egg to change a cave spider spawner into an enderman spawner. I used the moving wand in survival with the experience being used instead of power, and after one enderman spawned, it changed back to cave spider. Is repeatable.

**Comment by McJty** [comment]
Fixed next release
