### ISSUE TITLE
Master Protection Wand - Limited

### ISSUE THREAD

**Issue by Tifinchi** [romelo333/notenoughwands#74]
I love the protection wand, but the number of blocks is so limited. Is there any way I can adjust this manually in the configuration file please?

**Comment by McJty** [comment]
yes, this is a config option (protection_wand_maximumProtectedBlocks)

**Comment by Tifinchi** [comment]
I have no idea how to implement the code you gave me into the config file

**Comment by McJty** [comment]
That code is already there. Just search for it and change the default value (which is now set to 16)

**Comment by Tifinchi** [comment]
# Configuration file

captureblacklist {
    D:"minecraft:ender_dragon"=-1.0
    D:"minecraft:wither"=2.0
}


##########################################################################################################
# general
#--------------------------------------------------------------------------------------------------------#
# General configuration
##########################################################################################################

general {
    # If this is >= 1 then the protection data will be synced to the client with this frequency (in ticks). This makes protection cleaner at the cost of network traffic
    I:clientSideProtection=-1

    # If this is true then the protection wand will prevent ALL kind of interaction with protected blocks. If this is false then only block breaking is prevented
    B:interactionProtection=false

    # Set this to false if you don't want the durability bar for wands using RF
    B:showDurabilityBarForRF=true

    # A global setting to control all wands at once for RF/XP/Durability usage. If set to 'default' then every wand can configure this on its own (i.e. normal mode). You can also use 'easy_rf', 'normal_rf', or 'hard_rf' to set the wands to use RF in various difficulty modes [default: default]
    S:wandSettingPreset=default
}


movingblacklist {
    D:"minecraft:bedrock"=-1.0
    D:"minecraft:end_portal"=-1.0
    D:"minecraft:mob_spawner"=5.0
    D:"minecraft:portal"=-1.0
    D:"rftools:invisible_shield_block"=-1.0
    D:"rftools:notick_invisible_shield_block"=-1.0
    D:"rftools:notick_shield_block"=-1.0
    D:"rftools:shield_block"=-1.0
    D:"rftools:shield_block1"=-1.0
    D:"rftools:shield_block2"=-1.0
    D:"rftools:shield_block3"=-1.0
    D:"rftools:shield_block4"=-1.0
}


##########################################################################################################
# wandsettings
#--------------------------------------------------------------------------------------------------------#
# Wand configuration
##########################################################################################################

wandsettings {
}

**Comment by Tifinchi** [comment]
I cant find it

**Comment by McJty** [comment]
Um... that's strange. Your config is invalid. What version?

**Comment by Tifinchi** [comment]
http://www.mc-mod.net/not-enough-wands-mod/
This one with the link to 1.12.2

**Comment by Tifinchi** [comment]
fortunately it works great on my forge version and 1.12.2

**Comment by Tifinchi** [comment]
do you have a config file I could just copy and paste into the existing one to update it?

**Comment by Tifinchi** [comment]
still there?

**Comment by McJty** [comment]
Try to remove the config file first

**Comment by Tifinchi** [comment]
can you please give me a link to the proper download.. and I will just re-install

**Comment by McJty** [comment]
You can find the mod on curse. But I recommend first removing the config file. That will force the mod to recalculate it

**Comment by Tifinchi** [comment]
Ok.. I tried deleting the config.. but it repopulated with the same one. So I will try the curse file next

**Comment by Tifinchi** [comment]
This seems to have fixed the problem.. also something to note... that other file download never gave me an error when starting where this one forced me to install the McJtyLib.... I find it really strange that the other version even worked at all!

**Comment by Tifinchi** [comment]
My Config file has all the wand settings now though.. from downloading from curseforge...TY SO MUCH!

**Comment by McJty** [comment]
Yes, new Not Enough Wands requires McJtyLib
