### ISSUE TITLE
[1.12.2] Unable to detect Glazed Terracotta in Inventory

### ISSUE THREAD

**Issue by SnowShock35** [romelo333/notenoughwands#75]
#### Issue Details

- Minecraft 1.12.2
- Minecraft Forge 14.23.1.2587
- McJtyLib 2.6.2
- Not Enough Wands 1.6.0

#### Issue Description

Unable to swap glazed terracotta it says the block isn't found. Really quite odd given that it's a vanilla block.

#### Issue Media

![Issue Media #1](https://ss.blamesnow.co.uk/2018/01/1516724549-d6acf6df.png)

**Comment by McJty** [comment]
Fixed next release
