### ISSUE TITLE
Swapping wand failing to swap

### ISSUE THREAD

**Issue by robobeaver6** [romelo333/notenoughwands#97]
The swapping wand was working, but now it is not.  It is fully charged.
Minecraft 1.12.2
notenoughwands-1.12-1.7.3.jar

Shift right click to select type to change to successfully.
It used to be able to pull blocks from inventory or /Dank/null but now I will get the message:
'You need to hold a block in your offhand!'
or if I have the block in my off hand I get the message:
'You don't have the right block'

I have tried it with several block types including vanilla stone and dirt.
Game has been restarted.
Wand has been re-crafted.

It went a bit weird swapping Chisled marble blocks.  It was swapping them fine, then even on 5x5 it was only replacing one block after clicking it twice, now it doesn't replace any.

**Comment by McJty** [comment]
Read the tooltip of the end. You accidently got it into offhand mode. Just right click on the air to toggle it back

**Comment by robobeaver6** [comment]
Thanks That was the primary issue. It is replacing from inventory now.  I don't know why it didn't work in off hand mode though.  I had the correct blocks in the off hand and it still said it wasn't the right block
