### ISSUE TITLE
No class definiation Not enough wands crashes during loading

### ISSUE THREAD

**Issue by fivelow** [romelo333/notenoughwands#98]

**Comment by fivelow** [comment]
The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: Lromelo333/notenoughwands/proxy/CommonProxy;

This has been attempted with both Forge-14.23.5.2837 and forge-14.23.5.2816


[crash-2019-05-11_13.22.13-client.txt](https://github.com/romelo333/notenoughwands/files/3169307/crash-2019-05-11_13.22.13-client.txt)

---- Minecraft Crash Report ----

WARNING: coremods are present:
  AstralCore (astralsorcery-1.12.2-1.10.18.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.57-core.jar)
  BCModPlugin (backpacks 1.12.2 - 3.5.5.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  CoreMod (Aroma1997Core-1.12.2-2.0.0.2.b165.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.3.146.jar)
  ForgelinPlugin (Forgelin-1.8.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 5/11/19 1:22 PM
Description: Initializing game

java.lang.NoClassDefFoundError: Lromelo333/notenoughwands/proxy/CommonProxy;
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
	at java.lang.Class.getDeclaredField(Class.java:2068)
	at net.minecraftforge.fml.common.ProxyInjector.inject(ProxyInjector.java:70)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:611)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:593)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: romelo333.notenoughwands.proxy.CommonProxy
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 40 more
Caused by: java.lang.NoClassDefFoundError: mcjty/lib/proxy/AbstractCommonProxy
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 42 more
Caused by: java.lang.ClassNotFoundException: mcjty.lib.proxy.AbstractCommonProxy
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 46 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
	at java.lang.Class.getDeclaredField(Class.java:2068)
	at net.minecraftforge.fml.common.ProxyInjector.inject(ProxyInjector.java:70)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:611)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:593)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 556290368 bytes (530 MB) / 2381840384 bytes (2271 MB) up to 6623330304 bytes (6316 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx7106m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2837 132 mods loaded, 132 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                       | Version           | Source                                                      | Signature                                |
	|:----- |:------------------------ |:----------------- |:----------------------------------------------------------- |:---------------------------------------- |
	| LC    | minecraft                | 1.12.2            | minecraft.jar                                               | None                                     |
	| LC    | mcp                      | 9.42              | minecraft.jar                                               | None                                     |
	| LC    | FML                      | 8.0.99.99         | forge-1.12.2-14.23.5.2837.jar                               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | forge                    | 14.23.5.2837      | forge-1.12.2-14.23.5.2837.jar                               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | openmodscore             | 0.12.2            | minecraft.jar                                               | None                                     |
	| LC    | opencomputers|core       | 1.7.3.146         | minecraft.jar                                               | None                                     |
	| LC    | yac                      | 2.2.003           | YetAnotherCore-2.2.003-MC1.12.2.jar                         | None                                     |
	| LC    | actuallyadditions        | 1.12.2-r147       | ActuallyAdditions-1.12.2-r147.jar                           | None                                     |
	| LC    | crafttweaker             | 4.1.17            | CraftTweaker2-1.12-4.1.17.jar                               | None                                     |
	| LC    | mtlib                    | 3.0.6             | MTLib-3.0.6.jar                                             | None                                     |
	| LC    | modtweaker               | 4.0.17            | modtweaker-4.0.17.jar                                       | None                                     |
	| LC    | jei                      | 4.15.0.278        | jei_1.12.2-4.15.0.278.jar                                   | None                                     |
	| LC    | appleskin                | 1.0.9             | AppleSkin-mc1.12-1.0.9.jar                                  | None                                     |
	| LC    | ctm                      | MC1.12.2-0.3.3.22 | CTM-MC1.12.2-0.3.3.22.jar                                   | None                                     |
	| LC    | appliedenergistics2      | rv6-stable-6      | appliedenergistics2-rv6-stable-6.jar                        | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LC    | aroma1997core            | 2.0.0.2.b165      | Aroma1997Core-1.12.2-2.0.0.2.b165.jar                       | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| LC    | aroma1997sdimension      | 2.0.0.2.b92       | Aroma1997s-Dimensional-World-1.12.2-2.0.0.2.b92.jar         | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| LC    | baubles                  | 1.5.2             | Baubles-1.12-1.5.2.jar                                      | None                                     |
	| LC    | astralsorcery            | 1.10.18           | astralsorcery-1.12.2-1.10.18.jar                            | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| LC    | backpacks16840           | 3.5.5             | backpacks 1.12.2 - 3.5.5.jar                                | None                                     |
	| LC    | bdlib                    | 1.14.3.12         | bdlib-1.14.3.12-mc1.12.2.jar                                | None                                     |
	| LC    | bibliocraft              | 2.4.5             | BiblioCraft[v2.4.5][MC1.12.2].jar                           | None                                     |
	| LC    | bonsaitrees              | 1.1.2             | bonsaitrees-1.1.2-b144.jar                                  | None                                     |
	| LC    | bookshelf                | 2.3.577           | Bookshelf-1.12.2-2.3.577.jar                                | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LC    | thaumcraft               | 6.1.BETA26        | Thaumcraft-1.12.2-6.1.BETA26.jar                            | None                                     |
	| LC    | botania                  | r1.10-361         | Botania r1.10-361.jar                                       | None                                     |
	| LC    | buildcraftlib            | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                                | None                                     |
	| LC    | buildcraftcore           | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                                | None                                     |
	| LC    | buildcraftbuilders       | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                                | None                                     |
	| LC    | buildcrafttransport      | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                                | None                                     |
	| LC    | buildcraftsilicon        | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                                | None                                     |
	| LC    | tesla                    | 1.0.63            | Tesla-1.12.2-1.0.63.jar                                     | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LC    | theoneprobe              | 1.4.28            | theoneprobe-1.12-1.4.28.jar                                 | None                                     |
	| LC    | buildcraftcompat         | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                                | None                                     |
	| LC    | buildcraftenergy         | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                                | None                                     |
	| LC    | buildcraftfactory        | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                                | None                                     |
	| LC    | buildcraftrobotics       | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                                | None                                     |
	| LC    | chameleon                | 1.12-4.1.3        | Chameleon-1.12-4.1.3.jar                                    | None                                     |
	| LC    | chickens                 | 6.1.0             | chickens-6.1.0.jar                                          | None                                     |
	| LC    | chisel                   | MC1.12.2-0.2.1.35 | Chisel-MC1.12.2-0.2.1.35.jar                                | None                                     |
	| LC    | chiselsandbits           | 14.32             | chiselsandbits-14.32.jar                                    | None                                     |
	| LC    | codechickenlib           | 3.2.2.353         | CodeChickenLib-1.12.2-3.2.2.353-universal.jar               | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | redstoneflux             | 2.1.0             | RedstoneFlux-1.12-2.1.0.6-universal.jar                     | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | cofhcore                 | 4.6.2             | CoFHCore-1.12.2-4.6.2.25-universal.jar                      | None                                     |
	| LC    | cofhworld                | 1.3.0             | CoFHWorld-1.12.2-1.3.0.6-universal.jar                      | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | cyclopscore              | 1.2.0             | CyclopsCore-1.12.2-1.2.0.jar                                | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LC    | colossalchests           | 1.7.1             | ColossalChests-1.12.2-1.7.1.jar                             | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LC    | ic2                      | 2.8.152-ex112     | industrialcraft-2-2.8.152-ex112.jar                         | de041f9f6187debbc77034a344134053277aa3b0 |
	| LC    | commoncapabilities       | 2.2.1             | CommonCapabilities-1.12.2-2.2.1.jar                         | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LC    | refinedstorage           | 1.6.14            | refinedstorage-1.6.14.jar                                   | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
	| LC    | compactmachines3         | 3.0.18            | compactmachines3-1.12.2-3.0.18-b278.jar                     | None                                     |
	| LC    | cookingforblockheads     | 6.4.70            | CookingForBlockheads_1.12.2-6.4.70.jar                      | None                                     |
	| LC    | ctgui                    | 1.0.0             | CraftTweaker2-1.12-4.1.17.jar                               | None                                     |
	| LC    | crafttweakerjei          | 2.0.3             | CraftTweaker2-1.12-4.1.17.jar                               | None                                     |
	| LC    | creeperconfetti          | 1.4.2             | creeperconfetti-1.4.2.jar                                   | None                                     |
	| LC    | cropdusting              | 0.7               | CropDusting-0.7-[1.12.2].jar                                | None                                     |
	| LC    | cucumber                 | 1.1.3             | Cucumber-1.12.2-1.1.3.jar                                   | None                                     |
	| LC    | cyclicmagic              | 1.19.9            | Cyclic-1.12.2-1.19.9.jar                                    | 1bc8f8dbe770187a854cef35dad0ff40ba441bbe |
	| LC    | waila                    | 1.8.26            | Hwyla-1.8.26-B41_1.12.2.jar                                 | None                                     |
	| LC    | mantle                   | 1.12-1.3.3.49     | Mantle-1.12-1.3.3.49.jar                                    | None                                     |
	| LC    | twilightforest           | 3.8.689           | twilightforest-1.12.2-3.8.689-universal.jar                 | None                                     |
	| LC    | tconstruct               | 1.12.2-2.12.0.135 | TConstruct-1.12.2-2.12.0.135.jar                            | None                                     |
	| LC    | p455w0rdslib             | 2.1.44            | p455w0rdslib-1.12.2-2.1.44.jar                              | None                                     |
	| LC    | danknull                 | 1.4.46            | DankNull-1.12-1.4.46.jar                                    | None                                     |
	| LC    | darkutils                | 1.8.226           | DarkUtils-1.12.2-1.8.226.jar                                | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LC    | orespawn                 | 3.3.0             | OreSpawn-1.12-3.3.0.155.jar                                 | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LC    | densemetals              | 1.2.0             | DenseMetals-1.12-1.2.0.21.jar                               | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LC    | diethopper               | 1.1               | diethopper-1.1.jar                                          | None                                     |
	| LC    | enchdesc                 | 1.1.13            | EnchantmentDescriptions-1.12.2-1.1.13.jar                   | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LC    | endercore                | 1.12.2-0.5.57     | EnderCore-1.12.2-0.5.57.jar                                 | None                                     |
	| LC    | enderstorage             | 2.4.5.135         | EnderStorage-1.12.2-2.4.5.135-universal.jar                 | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | extrautils2              | 1.0               | extrautils2-1.12-1.9.9.jar                                  | None                                     |
	| LC    | opencomputers            | 1.7.3.146         | OpenComputers-MC1.12.2-1.7.3.146.jar                        | None                                     |
	| LC    | zerocore                 | 1.12.2-0.1.2.8    | zerocore-1.12.2-0.1.2.8.jar                                 | None                                     |
	| LC    | bigreactors              | 1.12.2-0.4.5.66   | ExtremeReactors-1.12.2-0.4.5.66.jar                         | None                                     |
	| LC    | fastleafdecay            | v14               | FastLeafDecay-v14.jar                                       | None                                     |
	| LC    | foodexpansion            | 1.3               | FoodExpansion1.3.3-1.12.2.jar                               | None                                     |
	| LC    | forgelin                 | 1.8.2             | Forgelin-1.8.2.jar                                          | None                                     |
	| LC    | ftblib                   | 5.4.1.99          | FTBLib-5.4.1.99.jar                                         | None                                     |
	| LC    | ftbutilities             | 5.4.0.96          | FTBUtilities-5.4.0.96.jar                                   | None                                     |
	| LC    | ftbbackups               | 0.0.0.ftbbackups  | FTBUtilitiesBackups-1.0.0.3.jar                             | None                                     |
	| LC    | giacomos_fishing_net     | 1.6.1             | GiacomosFishingNet-1.12.2-1.6.1.jar                         | None                                     |
	| LC    | modularrouters           | 1.12.2-3.2.1      | modular-routers-1.12.2-3.2.1.jar                            | None                                     |
	| LC    | overlord                 | 2.4.14            | Overlord-1.12.2-2.4.14.jar                                  | None                                     |
	| LC    | guideapi                 | 1.12-2.1.8-63     | Guide-API-1.12-2.1.8-63.jar                                 | None                                     |
	| LC    | hatchery                 | 2.2.1             | hatchery-1.12.2-2.2.1.jar                                   | None                                     |
	| LC    | thermalfoundation        | 2.6.2             | ThermalFoundation-1.12.2-2.6.2.26-universal.jar             | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | immersiveengineering     | 0.12-89           | ImmersiveEngineering-0.12-89.jar                            | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| LC    | immersivepetroleum       | 1.1.9             | immersivepetroleum-1.12.2-1.1.9.jar                         | None                                     |
	| LC    | teslacorelib             | 1.0.15            | tesla-core-lib-1.12.2-1.0.15.jar                            | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LC    | industrialforegoing      | 1.12.2-1.12.2     | industrialforegoing-1.12.2-1.12.2-226.jar                   | None                                     |
	| LC    | integrateddynamics       | 1.0.11            | IntegratedDynamics-1.12.2-1.0.11.jar                        | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LC    | integrateddynamicscompat | 1.0.0             | IntegratedDynamics-1.12.2-1.0.11.jar                        | None                                     |
	| LC    | integratedtunnels        | 1.5.6             | IntegratedTunnels-1.12.2-1.5.6.jar                          | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LC    | integratedtunnelscompat  | 1.0.0             | IntegratedTunnels-1.12.2-1.5.6.jar                          | None                                     |
	| LC    | ironbackpacks            | 1.12.2-3.0.8-12   | IronBackpacks-1.12.2-3.0.8-12.jar                           | None                                     |
	| LC    | ironchest                | 1.12.2-7.0.55.839 | ironchest-1.12.2-7.0.55.839.jar                             | None                                     |
	| LC    | iskalliumreactors        | 0.5.16            | iskalliumreactors-1.12.2-0.5.16.jar                         | None                                     |
	| LC    | jeiintegration           | 1.5.1.36          | jeiintegration_1.12.2-1.5.1.36.jar                          | None                                     |
	| LC    | llor                     | 1.1.6-mc1.12.2    | LLOverlayReloaded-1.1.6-mc1.12.2.jar                        | None                                     |
	| LC    | lootbags                 | 2.5.8.5           | LootBags-1.12.2-2.5.8.5.jar                                 | None                                     |
	| LC    | mcjtylib_ng              | 3.5.2             | mcjtylib-1.12-3.5.2.jar                                     | None                                     |
	| LC    | mcmultipart              | 2.5.3             | MCMultiPart-2.5.3.jar                                       | None                                     |
	| LC    | morechickens             | 3.2.0             | morechickens-1.12.2-3.2.0.jar                               | None                                     |
	| LC    | mysticalagriculture      | 1.7.5             | MysticalAgriculture-1.12.2-1.7.5.jar                        | None                                     |
	| LC    | natura                   | 1.12.2-4.3.2.66   | natura-1.12.2-4.3.2.66.jar                                  | None                                     |
	| LC    | nice                     | 0.4.0             | nice-1.12-0.4.0.jar                                         | None                                     |
	| L     | notenoughwands           | 1.7.1             | notenoughwands-1.12-1.7.1.jar                               | None                                     |
	| L     | openmods                 | 0.12.2            | OpenModsLib-1.12.2-0.12.2.jar                               | None                                     |
	| L     | openblocks               | 1.8.1             | OpenBlocks-1.12.2-1.8.1.jar                                 | None                                     |
	| L     | oreexcavation            | 1.4.133           | OreExcavation-1.4.133.jar                                   | None                                     |
	| L     | harvestcraft             | 1.12.2zb          | Pam's HarvestCraft 1.12.2zc The 7mm Kidney Stone Update.jar | None                                     |
	| L     | pneumaticcraft           | 1.12.2-0.10.5-346 | pneumaticcraft-repressurized-1.12.2-0.10.5-346.jar          | None                                     |
	| L     | rangedpumps              | 0.5               | rangedpumps-0.5.jar                                         | None                                     |
	| L     | rftools                  | 7.71              | rftools-1.12-7.71.jar                                       | None                                     |
	| L     | roost                    | 2.0.10            | roost-1.12.2-2.0.10.jar                                     | None                                     |
	| L     | simplyloaders            | 1.0.0             | Simplyloaders-2.0.jar                                       | None                                     |
	| L     | sonarcore                | 5.0.19            | sonarcore-1.12.2-5.0.19-20.jar                              | None                                     |
	| L     | storagedrawers           | 1.12-5.3.5        | StorageDrawers-1.12.2-5.3.8.jar                             | None                                     |
	| L     | storagedrawersextra      | @VERSION@         | StorageDrawersExtras-1.12-3.1.0.jar                         | None                                     |
	| L     | switchbow                | 1.5.6             | switchbow-1.5.6.jar                                         | None                                     |
	| L     | tt                       | 1.12.2            | tacotuesday-1.12.2-2.0.13.jar                               | None                                     |
	| L     | tc6aspects4jei           | 0.0.2a            | tc6aspects4jei-0.0.2a.jar                                   | None                                     |
	| L     | tcinventoryscan          | 2.0.10            | ThaumicInventoryScanning_1.12.2-2.0.10.jar                  | None                                     |
	| L     | thermalexpansion         | 5.5.3             | ThermalExpansion-1.12.2-5.5.3.41-universal.jar              | None                                     |
	| L     | thermalcultivation       | 0.3.2             | ThermalCultivation-1.12.2-0.3.2.11-universal.jar            | None                                     |
	| L     | thermaldynamics          | 2.5.4             | ThermalDynamics-1.12.2-2.5.4.18-universal.jar               | None                                     |
	| L     | vanilladeathchest        | 1.12.2-1.9.0.0    | vanilladeathchest-1.12.2-1.9.0.0.jar                        | None                                     |
	| L     | xaerominimap             | 1.16.7            | Xaeros_Minimap_1.16.7_Forge_1.12.jar                        | None                                     |
	| L     | xnet                     | 1.8.1             | xnet-1.12-1.8.1.jar                                         | None                                     |
	| L     | minimoos                 | 2.1-002           | MiniMoos-2.1.002-MC1.12.2.jar                               | None                                     |
	| L     | teslacorelib_registries  | 1.0.15            | tesla-core-lib-1.12.2-1.0.15.jar                            | None                                     |

	Loaded coremods (and transformers): 
AstralCore (astralsorcery-1.12.2-1.10.18.jar)
  
IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
EnderCorePlugin (EnderCore-1.12.2-0.5.57-core.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
BCModPlugin (backpacks 1.12.2 - 3.5.5.jar)
  brad16840.core.ClassTransformer
OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  openmods.core.OpenModsClassTransformer
CoreMod (Aroma1997Core-1.12.2-2.0.0.2.b165.jar)
  
TransformerLoader (OpenComputers-MC1.12.2-1.7.3.146.jar)
  li.cil.oc.common.asm.ClassTransformer
ForgelinPlugin (Forgelin-1.8.2.jar)
  
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.13544 Compatibility Profile Context 25.20.15011.1004' Renderer: 'Radeon (TM) RX 480 Graphics'
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
	AE2 Version: stable rv6-stable-6 for Forge 14.23.5.2768
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	Launched Version: forge-14.23.5.2837
	LWJGL: 2.9.4
	OpenGL: Radeon (TM) RX 480 Graphics GL version 4.6.13544 Compatibility Profile Context 25.20.15011.1004, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD A10-7850K Radeon R7, 12 Compute Cores 4C+8G

**Comment by McJty** [comment]
Update Not Enough Wands to 1.8.1

**Comment by fivelow** [comment]
This is what I get for trusting Twitch to have the latest version. Thanks for the help.
